[package]
name = "bevy_reactor_overlays"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { workspace = true }
bevy_reactor_signals = { workspace = true }
# bevy = "0.13.1"
bevy_mod_picking = "0.18.0"
bevy_reactor = { path = "../.." }
